### ISSUE TITLE
NoneType is not iterable

### ISSUE THREAD

**Issue by diek** [timbrel/GitSavvy#1007] opened 2018-09-14 14:45 UTC
- Sublime Text version number
3.1.1 build 3176

- Git version number
git version 2.18.0

- OS type and version
MacOS 10.13.6

- Console error output
Please report this error to GitSavvy:

argument of type 'NoneType' is not iterable

Traceback (most recent call last):
  File "/Users/diek/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package/core/git_command.py", line 215, in git
    stdout, stderr = self.decode_stdout(stdout), self.decode_stdout(stderr)
  File "/Users/diek/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package/core/git_command.py", line 266, in decode_stdout
    silent_fallback = self.savvy_settings.get("silent_fallback")
  File "/Users/diek/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package/core/settings.py", line 14, in get
    if key in project_savvy_settings:
TypeError: argument of type 'NoneType' is not iterable

- A description of the problem.
You told me to report it :) 

- Steps to reproduce, if possible
On startup, and restart of SBT

- If the bug is caused by a failing command, [include a debug log](https://github.com/divmain/GitSavvy/blob/master/docs/debug.md#providing-a-debug-log).

**Comment by stoivo** [comment] 2018-09-14 17:46
Do you use sublime-project ? how does for config project conf look?

I can't reproduce. Can you try to disable all other packages and check if that fixes the issue. Not that your not allowed to use any other packages then GitSavvy :D, but maybe there is a conflict.

**Comment by olets** [comment] 2018-09-18 15:16
Got the exact same error, possibly even at the same time — this laptop's been closed since Sept 13.

It's in a Sublime "project".

Added everything else to `User/Preferences.sublime-settings`'s `ignored_packages`, quit Sublime Text, reopened it, and didn't get the error. Removed everything from `ignored_packages`, quit and reopened, and didn't get the error. So… no helpful info there

**Comment by mradecki** [comment] 2018-09-19 05:57
Same issue

```
Please report this error to GitSavvy:

argument of type 'NoneType' is not iterable

Traceback (most recent call last):
  File "C:\Users\mr\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package\core/git_command.py", line 215, in git
    stdout, stderr = self.decode_stdout(stdout), self.decode_stdout(stderr)
  File "C:\Users\mr\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package\core/git_command.py", line 265, in decode_stdout
    fallback_encoding = self.savvy_settings.get("fallback_encoding")
  File "C:\Users\mr\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package\core/settings.py", line 14, in get
    if key in project_savvy_settings:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by kaste** [comment] 2019-10-23 09:36
Closing as fixed.

**Closed by kaste** 2019-10-23 09:36 UTC
Labels: bug, in progress
