### ISSUE TITLE
Commands not available in command palette when open project

### ISSUE THREAD

**Issue by srggrs** [timbrel/GitSavvy#1326] opened 2020-07-15 02:42 UTC
When I open sublime text only at start up and it does indexing the project folder, I noticed that the commands are not available in the command palette (for example I type "status" but `git: status` does not appear).

This happen when I open the sublime project and sublime run a re-indexing of the folder but only the first time that I open sublime after booting the OS, as I see the re-indexing happening and the CPU usage spikes. After that, I can't see the git savvy commands, but I need to close the project and re-open it to make them appear.

This does not happen if I open another project, and folder indexing is happening.

I hope these steps could help in reproduce the issue.

- Sublime version 3.2.2, build 3211
- git version 2.17.1
- OS Ubuntu 18.04.4 LTS

Here is the console output (where you can see it reloads Git Savvy):
```bash 
startup, version: 3211 linux x64 channel: stable
executable: /opt/sublime_text/sublime_text
working dir: /
zip path: /opt/sublime_text/Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.271506
startup time: 0.335452
first paint time: 0.355402
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.detect_indentation
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-pymdownx
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin A File Icon.plugin
reloading plugin ayu.activation
reloading plugin ayu.Icons
reloading plugin EditorConfig.EditorConfig
reloading plugin GitSavvy.__init__
reloading plugin GitSavvy.git_savvy
reloading plugin MarkdownPreview.markdown_preview
reloading plugin MarkdownPreview.markdown_settings
reloading plugin MarkdownPreview.markdown_wrapper
reloading plugin Material Theme.Icons
reloading plugin Material Theme.MT
reloading plugin Origami.origami
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin Pretty JSON.PrettyJson
reloading plugin Pretty JSON.PrettyJsonListeners
reloading plugin Python Breakpoints.PythonBreakpoints
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin Anaconda.anaconda
reloading plugin Anaconda.setup
reloading plugin Anaconda.version
reloading plugin Terminal.Terminal
plugins loaded
Package Control: Skipping automatic upgrade, last run at 2020-07-15 12:17:27, next run at 2020-07-15 13:17:27 or after
```

**Comment by kaste** [comment] 2020-07-15 09:47
Hi 👋!

> After that, I can't see the git savvy commands, but I need to close the project and re-open it to make them appear.

Just to be clear, does that mean you have to *restart* Sublime to make GitSavvy work again? 

The console output you posted is a basically a successful start, would be interesting how it looks if GitSavvy cannot be loaded or initialized.  Since we had a release in the last day or days it probably have tried to update this morning.  So maybe restarting the OS wasn't the problem at all (or re-indexing), maybe Package Control could not update the package for some reason. (Which could be anything: a file lock at the wrong time, a network failure.)

Is this really reproducible, t.i. on every OS restart?

**Comment by gwenzek** [comment] 2020-07-16 12:00
I also had an issue where GitSavvy wasn't loading properly after the last update.
I saw the update notes and afterward I noticed GitSavvy wasn't working.

Restarting Sublime did fix the issue.

**Comment by kaste** [comment] 2020-07-16 13:24
I'll have to make a hotfix release, hopefully today.  Let's see if the reloader works this time.

**Comment by kaste** [comment] 2020-07-18 13:41
A new hotfix release is underway.  Maybe open Sublime's console right after the next restart of Sublime or the OS, so you get a fuller picture of what's going on during such an update.

**Comment by srggrs** [comment] 2020-07-20 23:14
Hi people,

I posted the issue well aware of the limit of reproducibility, as you said could be anything, and being dependent by my OS set up. 
So thank you for looking into that! @kaste 

Seems that now, that I opened Sublime, I saw Git Savvy updated and reloaded, and I can see that it's working fine!

**Comment by kaste** [comment] 2020-09-16 12:17
Closing as possible a fluke.  I often run into PackageControl issues myself.  It feels like it is more designed around the happy path.  🤷

**Closed by kaste** 2020-09-16 12:17 UTC
