### ISSUE TITLE
Inline diff adding multiple instances of the same row

### ISSUE THREAD

**Issue by alextegelid** [timbrel/GitSavvy#133] opened 2015-03-24 10:52 UTC
When staging specific lines the line doesn't disappear after being added. This makes it possible to add the same row over and over again.

What I'm doing in the video is placing the cursor on row 92 `include('includes/php-session.php');` and pressing `l` (lowercase L), that row is then added on top of the changed hunk but are left where it was before aswell (row 93). I press `l` again and another "instance" of that row is added on top of the hunk (pushing the current row to row 94) and so forth... 

When typing the commit message later the diff shows 3 new lines will be added, all containing `include('includes/php-session.php');`

Screen recording: http://cl.ly/image/281L1M1O1F2t

I hope this makes sense, and if not I'll try to clarify it.

**Comment by divmain** [comment] 2015-03-26 00:42
Weird!  Makes sense, and I'll try to reproduce.  I've had a number of issues with inline-diff and no newlines at end of file.  Thanks for the heads-up!

**Comment by divmain** [comment] 2015-03-28 07:56
Still trying to come up with a solid approach to this.  The "No newline..." messages make it difficult.  I'll probably end up manually removing those lines from the diff output and making sure all the newlines at the end of the file display correctly...

**Comment by stoivo** [comment] 2015-10-09 21:05
@alextegelid, do you still have this issue? since I did some work on inline diff some weeks ago. Maybe it fixed this as well. I worked on adding a single line.

@divmain, I don't have any issues with new lines. Let's check who it is working now.

**Comment by alextegelid** [comment] 2015-10-10 06:12
I haven't noticed any problems in a while. It seems to be working fine. Good job!

I'll get back here if I notice anything weird.

**Comment by stoivo** [comment] 2015-10-31 09:07
Maybe close this one?

**Comment by alextegelid** [comment] 2015-10-31 10:01
Yeah, I still haven't noticed anything weird 👍🏼

**Comment by divmain** [comment] 2015-10-31 20:41
This still does not work correctly when there is no new line at the end of the file (either in index or working dir).  Going to leave this ticket open until it can be addressed.

**Comment by kaste** [comment] 2020-10-20 09:11
Closing. As I worked on the codebase here, I didn't find further bugs.

**Closed by kaste** 2020-10-20 09:11 UTC
Labels: bug, next
