### ISSUE TITLE
ValueError when pushing initial commit to empty repo 

### ISSUE THREAD

**Issue by braver** [timbrel/GitSavvy#1026] opened 2018-10-11 19:35 UTC
- Sublime Text version 3175
- Git version number 2.17.1 (Apple Git-112)
- OS type and version macOS 10.14
- Console error output:
```
Traceback (most recent call last):
  File "/Users/koenlageveen/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package/core/commands/push.py", line 67, in run_async
ValueError: need more than 1 value to unpack
```

- A description of the problem: I have created a [new repository](https://github.com/braver/SublimeMerge), cloned it, added some files and created the initial commit. Now I want to push, but it fails. I tried getting more debug logging, but don't get more output than I already shared here.

**Comment by asfaltboy** [comment] 2018-11-29 15:41
I could not reproduce the issue on dev, I think this was possibly a regression that we fixed but forgot to push hotfix... I do believe a release is imminent though, so this should be resolved soon.

**Comment by kaste** [comment] 2020-10-20 08:15
Closing as this should work

**Closed by kaste** 2020-10-20 08:15 UTC
Labels: bug, regression
