### ISSUE TITLE
Graph Current File is showing the branch not jut the file

### ISSUE THREAD

**Issue by luispuerto** [timbrel/GitSavvy#1301] opened 2020-05-02 19:58 UTC
Perhaps I'm doing something wrong but when I try to get a graph just with the commits of the file I'm working on I'm getting the whole branch. 

Is this the intended behavior or is there a bug?

**Comment by luispuerto** [comment] 2020-05-02 20:14
Shouldn't the `--sparse` option be removed with you are asking for just the graph history of a file?

**Comment by kaste** [comment] 2020-05-02 20:48
Hm, using "File History" (aliased as the old "graph current file") I get 

![image](https://user-images.githubusercontent.com/8558/80891813-ca14de80-8cc6-11ea-8fbd-d4fd312799c7.png)

which is not the whole branch. Do I have a special case here?  Can you show a screenshot as well?

**Comment by luispuerto** [comment] 2020-05-02 20:50
here is the screenshot

**Comment by kaste** [comment] 2020-05-02 21:02
"_includes/figure" is an extensionless file? 

You don't have any "..." lines here so that doesn't seem "ok" to me as well.  When you remove "--sparse", you also have to remove "--simplify-by-decoration", I think. At least I usually see them as a pair setting, just choosing "sparse" or "dense" (or ... some other mode I forgot). 

Other than that, you pasted our command to the terminal, yeah?

**Comment by kaste** [comment] 2020-05-02 21:04
Do you have the latest and greatest git version? Well, looks like you can use the "human" date format which was added a year ago, roughly.

**Comment by luispuerto** [comment] 2020-05-02 21:05
yeah… I copy&paste to check what was going on. 

The file is extensionless but it happens with other files with extension. 

I also update git often, so I have the last version.

**Comment by kaste** [comment] 2020-05-02 21:07
Is it that repo only?  Is this repo open source so I could check it out?

**Comment by luispuerto** [comment] 2020-05-02 21:07
This file was just added in the last commit: 

<img width="803" alt="image" src="https://user-images.githubusercontent.com/22882880/80892349-fc780900-8cd1-11ea-9f25-59aa3044ab80.png">

**Comment by luispuerto** [comment] 2020-05-02 21:09
you can check the [repo](https://github.com/luispuerto/luispuerto.net) but it happens with other repos

**Comment by kaste** [comment] 2020-05-02 21:28
Can reproduce 👌   Do you know *why* this works for some repos? What's the special case I'm hitting here?

**Comment by luispuerto** [comment] 2020-05-02 21:30
I have no idea. This is a jekyll repo… perhaps because of the structure or something like that.

**Comment by luispuerto** [comment] 2020-05-02 21:32
I really don't know if this is a special case, but I have other repos that produce the same output… and they aren't a jekyll repo.

**Comment by luispuerto** [comment] 2020-05-02 21:43
PS/ I have also sublime merge installed and there I can always see the file history correctly, so… I don't think it's related "only" to the repo.

**Comment by kaste** [comment] 2020-05-02 21:51
Reading the git log man page it is relatively clear *we* do it wrong here.  (And I also immediately found repos on my computer showing the bug.)  But it is so completely wrong that I still wonder why it reliable works for many other repos, of course the repos I actually used while writing this.  🤣

**Comment by luispuerto** [comment] 2020-05-02 21:52
😆 well, shit happens

**Comment by kaste** [comment] 2020-05-04 20:41
Fixed in https://github.com/timbrel/GitSavvy/releases/tag/2.22.4

**Closed by kaste** 2020-05-04 20:41 UTC
Labels: bug, critical

**Comment by luispuerto** [comment] 2020-05-05 04:31
Yeah! Now it's working as I understood it should. Thanks a lot for the swift response!
